# -*- coding: utf-8 -*-
"""MedFlow_AI_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWrIvEv2KLg-flxTsa-Q1KcEUhw8ecXD

# 🏦 MedFlow AI
## Agente Inteligente para Consulta de Protocolos Clínicos

Projeto desenvolvido para o Challenge Alura Agente utilizando
RAG — Retrieval-Augmented Generation.

### Objetivo
Criar um agente inteligente capaz de consultar documentos clínicos
e responder perguntas utilizando exclusivamente as informações
recuperadas da base de conhecimento.
"""

# ============================================================
# MEDFLOW AI - ETAPA 1
# Instalação das bibliotecas necessárias
# ============================================================

!pip install -q \
    pypdf \
    sentence-transformers \
    chromadb \
    langchain \
    langchain-community \
    langchain-text-splitters

print("✅ Bibliotecas instaladas com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 2
# Teste das bibliotecas instaladas
# ============================================================

import os
import chromadb

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
from langchain_text_splitters import RecursiveCharacterTextSplitter

print("✅ Ambiente do MedFlow AI pronto!")
print("ChromaDB:", chromadb.__version__)

# ============================================================
# MEDFLOW AI - ETAPA 3
# Upload dos PDFs da base de conhecimento
# ============================================================

from google.colab import files
import os

uploaded = files.upload()

print("\n📚 Arquivos enviados:\n")

for nome in uploaded.keys():
    print("-", nome)

# ============================================================
# MEDFLOW AI - ETAPA 3.1
# Conferência dos PDFs encontrados
# ============================================================

arquivos_pdf = [
    arquivo
    for arquivo in os.listdir("/content")
    if arquivo.lower().endswith(".pdf")
]

arquivos_pdf.sort()

print("📚 PDFs encontrados no MedFlow AI:\n")

for i, arquivo in enumerate(arquivos_pdf, start=1):
    print(f"{i}. {arquivo}")

print(f"\n✅ Total de PDFs encontrados: {len(arquivos_pdf)}")

!pip install -q pypdf

print("✅ pypdf instalado com sucesso!")

from pypdf import PdfReader

print("✅ PdfReader importado corretamente!")

import os

arquivos_pdf = [
    arquivo
    for arquivo in os.listdir("/content")
    if arquivo.lower().endswith(".pdf")
]

arquivos_pdf.sort()

print("📚 PDFs encontrados no MedFlow AI:\n")

for i, arquivo in enumerate(arquivos_pdf, start=1):
    print(f"{i}. {arquivo}")

print(f"\n✅ Total de PDFs encontrados: {len(arquivos_pdf)}")

# ============================================================
# MEDFLOW AI - ETAPA 4
# Leitura e extração do texto dos 5 PDFs
# ============================================================

from pypdf import PdfReader
import os

documentos = []

for arquivo in arquivos_pdf:

    caminho = os.path.join("/content", arquivo)

    reader = PdfReader(caminho)

    print(f"\n📄 Lendo: {arquivo}")
    print(f"   📑 Número de páginas: {len(reader.pages)}")

    for numero_pagina, pagina in enumerate(reader.pages, start=1):

        texto = pagina.extract_text()

        if texto and texto.strip():

            documentos.append({
                "fonte": arquivo,
                "pagina": numero_pagina,
                "texto": texto.strip()
            })

print("\n" + "=" * 60)
print("✅ EXTRAÇÃO CONCLUÍDA!")
print(f"📚 PDFs processados: {len(arquivos_pdf)}")
print(f"📑 Páginas com texto extraído: {len(documentos)}")
print("=" * 60)

!pip install -q langchain-text-splitters

print("✅ langchain-text-splitters instalado com sucesso!")



from langchain_text_splitters import RecursiveCharacterTextSplitter

print("✅ RecursiveCharacterTextSplitter importado corretamente!")

# ============================================================
# MEDFLOW AI - ETAPA 5
# Divisão dos textos em chunks
# ============================================================

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=["\n\n", "\n", ".", " ", ""]
)

chunks = []

for documento in documentos:
    partes = text_splitter.split_text(documento["texto"])

    for numero_chunk, parte in enumerate(partes, start=1):
        chunks.append({
            "fonte": documento["fonte"],
            "pagina": documento["pagina"],
            "chunk": numero_chunk,
            "texto": parte
        })

print("✅ CHUNKING CONCLUÍDO!")
print(f"📦 Total de chunks criados: {len(chunks)}")

# ============================================================
# MEDFLOW AI - ETAPA 5.1
# Conferência dos chunks criados
# ============================================================

print("📦 EXEMPLO DE CHUNK\n")

print("Fonte:", chunks[0]["fonte"])
print("Página:", chunks[0]["pagina"])
print("Chunk:", chunks[0]["chunk"])

print("\nTexto:\n")
print(chunks[0]["texto"])

!pip install -q sentence-transformers

print("✅ sentence-transformers instalado com sucesso!")

from sentence_transformers import SentenceTransformer

print("✅ SentenceTransformer importado corretamente!")

# ============================================================
# MEDFLOW AI - ETAPA 6
# Carregamento do modelo de embeddings
# ============================================================

from sentence_transformers import SentenceTransformer

modelo_embeddings = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("✅ Modelo de embeddings carregado com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 6.1
# Geração dos embeddings dos chunks
# ============================================================

textos_chunks = [item["texto"] for item in chunks]

embeddings = modelo_embeddings.encode(
    textos_chunks,
    show_progress_bar=True
)

print("✅ EMBEDDINGS CRIADOS COM SUCESSO!")
print(f"📦 Quantidade de chunks: {len(chunks)}")
print(f"🔢 Quantidade de embeddings: {len(embeddings)}")
print(f"📐 Dimensão de cada embedding: {len(embeddings[0])}")

!pip install -q chromadb

print("✅ ChromaDB instalado com sucesso!")

import chromadb

print("✅ ChromaDB importado corretamente!")
print("Versão:", chromadb.__version__)

# ============================================================
# MEDFLOW AI - ETAPA 7.1
# Criar ou recuperar a coleção do ChromaDB
# ============================================================

client = chromadb.Client()

collection = client.get_or_create_collection(
    name="medflow_protocolos"
)

print("✅ Coleção pronta para uso!")
print("Nome:", collection.name)

# ============================================================
# MEDFLOW AI - ETAPA 7.2
# Inserir chunks, embeddings e metadados no ChromaDB
# ============================================================

ids = []
documentos_chroma = []
metadados = []
embeddings_chroma = []

for i, item in enumerate(chunks):
    ids.append(f"chunk_{i}")

    documentos_chroma.append(
        item["texto"]
    )

    metadados.append({
        "fonte": item["fonte"],
        "pagina": item["pagina"],
        "chunk": item["chunk"]
    })

    embeddings_chroma.append(
        embeddings[i].tolist()
    )

collection.add(
    ids=ids,
    documents=documentos_chroma,
    metadatas=metadados,
    embeddings=embeddings_chroma
)

print("✅ DADOS INSERIDOS NO CHROMADB!")
print(f"📦 Total armazenado: {collection.count()}")

# ============================================================
# MEDFLOW AI - ETAPA 8
# Primeira busca semântica
# ============================================================

pergunta = "O que fazer quando o paciente relata alergia?"

embedding_pergunta = modelo_embeddings.encode(
    [pergunta]
)

resultado = collection.query(
    query_embeddings=embedding_pergunta.tolist(),
    n_results=3
)

print("🔎 PERGUNTA:")
print(pergunta)

print("\n📚 TRECHOS ENCONTRADOS:\n")

for i in range(len(resultado["documents"][0])):

    texto = resultado["documents"][0][i]
    metadata = resultado["metadatas"][0][i]

    print(f"--- Resultado {i + 1} ---")
    print("Fonte:", metadata["fonte"])
    print("Página:", metadata["pagina"])
    print("Chunk:", metadata["chunk"])

    print("\nTexto:")
    print(texto)

    print("\n" + "=" * 70 + "\n")

# ============================================================
# MEDFLOW AI - ETAPA 8.1
# Testar a relevância dos resultados encontrados
# ============================================================

pergunta = "O que fazer quando o paciente relata alergia?"

embedding_pergunta = modelo_embeddings.encode([pergunta])

resultado = collection.query(
    query_embeddings=embedding_pergunta.tolist(),
    n_results=5,
    include=["documents", "metadatas", "distances"]
)

print("🔎 PERGUNTA:")
print(pergunta)

print("\n📚 RESULTADOS POR RELEVÂNCIA:\n")

for i in range(len(resultado["documents"][0])):

    texto = resultado["documents"][0][i]
    metadata = resultado["metadatas"][0][i]
    distancia = resultado["distances"][0][i]

    print(f"--- Resultado {i + 1} ---")
    print(f"📊 Distância: {distancia:.4f}")
    print("📄 Fonte:", metadata["fonte"])
    print("📑 Página:", metadata["pagina"])
    print("📦 Chunk:", metadata["chunk"])

    print("\n📝 Texto:")
    print(texto[:600])

    print("\n" + "=" * 70 + "\n")

# ============================================================
# MEDFLOW AI - ETAPA 8.2
# Modelo de embeddings multilíngue
# ============================================================

from sentence_transformers import SentenceTransformer

modelo_embeddings = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

print("✅ Modelo multilíngue carregado com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 8.3
# Geração dos embeddings com o modelo multilíngue
# ============================================================

textos_chunks = [item["texto"] for item in chunks]

embeddings_multilingue = modelo_embeddings.encode(
    textos_chunks,
    show_progress_bar=True
)

print("✅ NOVOS EMBEDDINGS CRIADOS!")
print(f"📦 Quantidade de chunks: {len(chunks)}")
print(f"🔢 Quantidade de embeddings: {len(embeddings_multilingue)}")
print(f"📐 Dimensão de cada embedding: {len(embeddings_multilingue[0])}")

# ============================================================
# MEDFLOW AI - ETAPA 8.4
# Criar nova coleção para embeddings multilíngues
# ============================================================

collection_multilingue = client.get_or_create_collection(
    name="medflow_protocolos_multilingue"
)

print("✅ Nova coleção multilíngue pronta!")
print("Nome:", collection_multilingue.name)

# ============================================================
# MEDFLOW AI - ETAPA 8.5
# Inserir chunks e embeddings multilíngues no ChromaDB
# ============================================================

ids_multilingue = []
documentos_multilingue = []
metadados_multilingue = []
vetores_multilingue = []

for i, item in enumerate(chunks):
    ids_multilingue.append(f"chunk_multi_{i}")

    documentos_multilingue.append(
        item["texto"]
    )

    metadados_multilingue.append({
        "fonte": item["fonte"],
        "pagina": item["pagina"],
        "chunk": item["chunk"]
    })

    vetores_multilingue.append(
        embeddings_multilingue[i].tolist()
    )

collection_multilingue.add(
    ids=ids_multilingue,
    documents=documentos_multilingue,
    metadatas=metadados_multilingue,
    embeddings=vetores_multilingue
)

print("✅ DADOS MULTILÍNGUES INSERIDOS NO CHROMADB!")
print(f"📦 Total armazenado: {collection_multilingue.count()}")

# ============================================================
# MEDFLOW AI - ETAPA 8.6
# Teste da busca semântica com embeddings multilíngues
# ============================================================

pergunta = "O que fazer quando o paciente relata alergia?"

embedding_pergunta_multi = modelo_embeddings.encode(
    [pergunta]
)

resultado_multi = collection_multilingue.query(
    query_embeddings=embedding_pergunta_multi.tolist(),
    n_results=5,
    include=["documents", "metadatas", "distances"]
)

print("🔎 PERGUNTA:")
print(pergunta)

print("\n📚 RESULTADOS MULTILÍNGUES:\n")

for i in range(len(resultado_multi["documents"][0])):

    texto = resultado_multi["documents"][0][i]
    metadata = resultado_multi["metadatas"][0][i]
    distancia = resultado_multi["distances"][0][i]

    print(f"--- Resultado {i + 1} ---")
    print(f"📊 Distância: {distancia:.4f}")
    print("📄 Fonte:", metadata["fonte"])
    print("📑 Página:", metadata["pagina"])
    print("📦 Chunk:", metadata["chunk"])

    print("\n📝 Texto:")
    print(texto[:600])

    print("\n" + "=" * 70 + "\n")

# ============================================================
# MEDFLOW AI - ETAPA 8.7
# Normalização dos embeddings multilíngues
# ============================================================

embeddings_normalizados = modelo_embeddings.encode(
    textos_chunks,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("✅ EMBEDDINGS NORMALIZADOS CRIADOS!")
print(f"📦 Quantidade: {len(embeddings_normalizados)}")
print(f"📐 Dimensão: {len(embeddings_normalizados[0])}")

# ============================================================
# MEDFLOW AI - ETAPA 8.8
# Criar coleção com similaridade por cosseno
# ============================================================

collection_cosine = client.get_or_create_collection(
    name="medflow_protocolos_cosine",
    metadata={"hnsw:space": "cosine"}
)

print("✅ Coleção com similaridade por cosseno criada!")
print("Nome:", collection_cosine.name)

# ============================================================
# MEDFLOW AI - ETAPA 8.9
# Inserir chunks com embeddings normalizados
# ============================================================

ids_cosine = []
documentos_cosine = []
metadados_cosine = []
vetores_cosine = []

for i, item in enumerate(chunks):
    ids_cosine.append(f"chunk_cosine_{i}")

    documentos_cosine.append(
        item["texto"]
    )

    metadados_cosine.append({
        "fonte": item["fonte"],
        "pagina": item["pagina"],
        "chunk": item["chunk"]
    })

    vetores_cosine.append(
        embeddings_normalizados[i].tolist()
    )

collection_cosine.add(
    ids=ids_cosine,
    documents=documentos_cosine,
    metadatas=metadados_cosine,
    embeddings=vetores_cosine
)

print("✅ DADOS INSERIDOS NA COLEÇÃO COSINE!")
print(f"📦 Total armazenado: {collection_cosine.count()}")

# ============================================================
# MEDFLOW AI - ETAPA 8.10
# Teste final da busca com cosseno + embeddings normalizados
# ============================================================

pergunta = "O que fazer quando o paciente relata alergia?"

embedding_pergunta_cosine = modelo_embeddings.encode(
    [pergunta],
    normalize_embeddings=True
)

resultado_cosine = collection_cosine.query(
    query_embeddings=embedding_pergunta_cosine.tolist(),
    n_results=5,
    include=["documents", "metadatas", "distances"]
)

print("🔎 PERGUNTA:")
print(pergunta)

print("\n📚 RESULTADOS COM COSINE:\n")

for i in range(len(resultado_cosine["documents"][0])):

    texto = resultado_cosine["documents"][0][i]
    metadata = resultado_cosine["metadatas"][0][i]
    distancia = resultado_cosine["distances"][0][i]

    similaridade = 1 - distancia

    print(f"--- Resultado {i + 1} ---")
    print(f"📊 Distância: {distancia:.4f}")
    print(f"🎯 Similaridade aproximada: {similaridade:.4f}")
    print("📄 Fonte:", metadata["fonte"])
    print("📑 Página:", metadata["pagina"])
    print("📦 Chunk:", metadata["chunk"])

    print("\n📝 Texto:")
    print(texto[:700])

    print("\n" + "=" * 70 + "\n")

# ============================================================
# MEDFLOW AI - ETAPA 9
# Função de recuperação de contexto
# ============================================================

def buscar_contexto(pergunta, quantidade=3):

    # Transformar a pergunta em embedding normalizado
    embedding_pergunta = modelo_embeddings.encode(
        [pergunta],
        normalize_embeddings=True
    )

    # Buscar os trechos mais relevantes no ChromaDB
    resultado = collection_cosine.query(
        query_embeddings=embedding_pergunta.tolist(),
        n_results=quantidade,
        include=["documents", "metadatas", "distances"]
    )

    contextos = []

    for i in range(len(resultado["documents"][0])):

        contexto = {
            "texto": resultado["documents"][0][i],
            "fonte": resultado["metadatas"][0][i]["fonte"],
            "pagina": resultado["metadatas"][0][i]["pagina"],
            "chunk": resultado["metadatas"][0][i]["chunk"],
            "similaridade": 1 - resultado["distances"][0][i]
        }

        contextos.append(contexto)

    return contextos


print("✅ Função buscar_contexto criada com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 9.1
# Teste da função buscar_contexto
# ============================================================

pergunta_teste = "O que fazer se o paciente não cumpriu o jejum?"

resultados_teste = buscar_contexto(
    pergunta_teste,
    quantidade=3
)

print("🔎 PERGUNTA:")
print(pergunta_teste)

print("\n📚 CONTEXTOS RECUPERADOS:\n")

for i, item in enumerate(resultados_teste, start=1):

    print(f"--- Resultado {i} ---")
    print(f"🎯 Similaridade: {item['similaridade']:.4f}")
    print("📄 Fonte:", item["fonte"])
    print("📑 Página:", item["pagina"])
    print("📦 Chunk:", item["chunk"])

    print("\n📝 Texto:")
    print(item["texto"][:800])

    print("\n" + "=" * 70 + "\n")

# ============================================================
# MEDFLOW AI - ETAPA 10
# Montar contexto para a IA generativa
# ============================================================

def montar_contexto(pergunta, quantidade=3):

    resultados = buscar_contexto(
        pergunta,
        quantidade=quantidade
    )

    partes_contexto = []

    for item in resultados:

        bloco = f"""
Fonte: {item['fonte']}
Página: {item['pagina']}

{item['texto']}
"""

        partes_contexto.append(bloco.strip())

    contexto_final = "\n\n---\n\n".join(partes_contexto)

    return contexto_final


print("✅ Função montar_contexto criada com sucesso!")

pergunta = "O que fazer se o paciente não cumpriu o jejum?"

contexto = montar_contexto(pergunta)

print("📚 CONTEXTO QUE SERÁ ENVIADO À IA:\n")
print(contexto)

# ============================================================
# MEDFLOW AI - ETAPA 11
# Construção do prompt para a IA generativa
# ============================================================

def criar_prompt(pergunta, contexto):

    prompt = f"""
Você é o MedFlow AI, um assistente inteligente para consulta de
protocolos e documentos clínicos.

Sua tarefa é responder à pergunta do usuário utilizando APENAS
as informações presentes no contexto fornecido.

Regras:
1. Não invente informações.
2. Não utilize conhecimento externo ao contexto.
3. Se a resposta não estiver disponível no contexto, diga:
   "Não encontrei essa informação na base de conhecimento."
4. Seja claro, objetivo e profissional.
5. Não faça diagnóstico, prescrição ou substitua avaliação profissional.
6. Quando possível, informe a fonte utilizada.

CONTEXTO:
{contexto}

PERGUNTA:
{pergunta}

RESPOSTA:
"""

    return prompt


print("✅ Função criar_prompt criada com sucesso!")

pergunta = "O que fazer se o paciente não cumpriu o jejum?"

contexto = montar_contexto(pergunta)

prompt_teste = criar_prompt(
    pergunta,
    contexto
)

print(prompt_teste)

!pip install -q -U google-genai

print("✅ SDK google-genai instalado com sucesso!")

import os
from getpass import getpass

os.environ["GEMINI_API_KEY"] = getpass("Cole sua API Key do Gemini: ")

print("✅ API Key configurada com sucesso!")

from google import genai
import os

client_gemini = genai.Client(
    api_key=os.environ["GEMINI_API_KEY"]
)

print("✅ Cliente Gemini criado com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 11.4
# Primeira resposta RAG usando Gemini 3.6 Flash
# ============================================================

pergunta = "O que fazer se o paciente não cumpriu o jejum?"

# 1. Buscar informações relevantes nos PDFs
contexto = montar_contexto(
    pergunta,
    quantidade=3
)

# 2. Montar o prompt do MedFlow AI
prompt = criar_prompt(
    pergunta,
    contexto
)

# 3. Enviar para o Gemini
response = client_gemini.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt
)

print("🤖 MEDFLOW AI\n")
print("Pergunta:", pergunta)

print("\nResposta:")
print(response.text)

# ============================================================
# MEDFLOW AI - ETAPA 12
# Função final do agente RAG
# ============================================================

def responder_medflow(pergunta, quantidade_contextos=3):

    # 1. Buscar os trechos mais relevantes
    contexto = montar_contexto(
        pergunta,
        quantidade=quantidade_contextos
    )

    # 2. Criar o prompt
    prompt = criar_prompt(
        pergunta,
        contexto
    )

    # 3. Enviar para o Gemini
    resposta = client_gemini.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    # 4. Exibir resultado
    print("🤖 MEDFLOW AI")
    print("=" * 60)

    print("\n❓ Pergunta:")
    print(pergunta)

    print("\n💬 Resposta:")
    print(resposta.text)

    print("\n" + "=" * 60)

    return resposta.text


print("✅ Função responder_medflow criada com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 12.1
# Teste do agente com uma nova pergunta
# ============================================================

responder_medflow(
    "O que fazer se houver divergência entre o lado informado pelo paciente e a documentação?"
)

# ============================================================
# MEDFLOW AI - ETAPA 12.2
# Teste com informação que não existe na base
# ============================================================

responder_medflow(
    "Qual antibiótico deve ser administrado antes da cirurgia?"
)

# ============================================================
# MEDFLOW AI - ETAPA 13
# Instalação do Gradio para interface
# ============================================================

!pip install -q gradio

print("✅ Gradio instalado com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 13.1
# Função para conectar a interface ao agente
# ============================================================

def interface_medflow(pergunta):

    if not pergunta or not pergunta.strip():
        return "Digite uma pergunta para consultar a base de conhecimento."

    contexto = montar_contexto(
        pergunta,
        quantidade=3
    )

    prompt = criar_prompt(
        pergunta,
        contexto
    )

    resposta = client_gemini.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    return resposta.text


print("✅ Função da interface criada com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 13.2
# Interface visual com Gradio
# ============================================================

import gradio as gr

with gr.Blocks(title="MedFlow AI") as app:

    gr.Markdown(
        """
        # 🏥 MedFlow AI

        ### Assistente Inteligente para Consulta de Protocolos Clínicos

        **Conectando conhecimento, melhorando decisões, cuidando de vidas.**

        Faça uma pergunta sobre os documentos disponíveis na base de conhecimento.
        O MedFlow AI responderá utilizando as informações recuperadas dos protocolos.
        """
    )

    pergunta = gr.Textbox(
        label="Sua pergunta",
        placeholder="Ex.: O que fazer se o paciente não cumpriu o jejum?",
        lines=2
    )

    botao = gr.Button(
        "Perguntar ao MedFlow AI"
    )

    resposta = gr.Markdown(
        label="Resposta"
    )

    botao.click(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    gr.Examples(
        examples=[
            ["O que fazer se o paciente não cumpriu o jejum?"],
            ["O que fazer quando o paciente relata alergia?"],
            ["Como proceder se houver divergência de lateralidade?"],
            ["O que fazer quando um termo obrigatório está pendente?"],
            ["Qual antibiótico deve ser administrado antes da cirurgia?"]
        ],
        inputs=pergunta
    )

print("✅ Interface do MedFlow AI criada com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 13.4
# Interface profissional estilo website
# ============================================================

import gradio as gr

# Fecha a interface anterior, se estiver ativa
try:
    app.close()
except:
    pass


css_medflow = """
/* Fundo geral */
.gradio-container {
    max-width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
    background:
        radial-gradient(circle at top right, rgba(0, 194, 209, 0.10), transparent 35%),
        linear-gradient(180deg, #f7fbfd 0%, #eef7fa 100%);
    font-family: Inter, Arial, sans-serif;
}

/* Container principal */
#medflow-main {
    max-width: 1180px;
    margin: 0 auto;
    padding: 0 28px 40px 28px;
}

/* Hero */
.hero-medflow {
    background: linear-gradient(135deg, #002f57 0%, #005f8f 55%, #00a7b5 100%);
    border-radius: 0 0 32px 32px;
    padding: 52px 48px;
    color: white;
    box-shadow: 0 18px 50px rgba(0, 56, 92, 0.18);
    margin-bottom: 28px;
}

.hero-badge {
    display: inline-block;
    padding: 7px 14px;
    background: rgba(255,255,255,0.13);
    border: 1px solid rgba(255,255,255,0.22);
    border-radius: 30px;
    font-size: 13px;
    font-weight: 600;
    letter-spacing: .4px;
    margin-bottom: 18px;
}

.hero-medflow h1 {
    font-size: 44px;
    line-height: 1.05;
    margin: 0 0 12px 0;
    color: white;
}

.hero-medflow p {
    font-size: 17px;
    line-height: 1.6;
    max-width: 760px;
    margin: 0;
    color: rgba(255,255,255,0.90);
}

.hero-slogan {
    margin-top: 18px !important;
    font-size: 14px !important;
    font-weight: 600;
    letter-spacing: .4px;
    color: #bffaff !important;
}

/* Cards */
.info-card {
    background: white;
    border: 1px solid #dcecf2;
    border-radius: 18px;
    padding: 22px;
    box-shadow: 0 8px 24px rgba(31, 73, 95, 0.06);
    min-height: 118px;
}

.info-card h3 {
    margin: 0 0 8px 0;
    color: #003a6b;
    font-size: 16px;
}

.info-card p {
    margin: 0;
    color: #5d7180;
    font-size: 13px;
    line-height: 1.5;
}

/* Área principal da pergunta */
#consulta-card {
    background: white;
    border-radius: 24px;
    border: 1px solid #d8eaf0;
    padding: 26px !important;
    box-shadow: 0 15px 40px rgba(0, 72, 105, 0.08);
    margin-top: 18px;
}

.section-title {
    color: #003a6b;
    font-size: 21px;
    font-weight: 700;
    margin-bottom: 4px;
}

.section-subtitle {
    color: #687f8d;
    font-size: 14px;
    margin-bottom: 18px;
}

/* Campo de pergunta */
#pergunta-medflow textarea {
    border-radius: 15px !important;
    border: 1px solid #c9dfe7 !important;
    font-size: 15px !important;
    padding: 16px !important;
    background: #fbfdfe !important;
}

#pergunta-medflow textarea:focus {
    border-color: #00a7b5 !important;
    box-shadow: 0 0 0 3px rgba(0,167,181,0.10) !important;
}

/* Botão principal */
#botao-medflow {
    background: linear-gradient(90deg, #005f8f, #00a7b5) !important;
    color: white !important;
    font-weight: 700 !important;
    border: none !important;
    border-radius: 14px !important;
    min-height: 48px !important;
    font-size: 15px !important;
    box-shadow: 0 8px 20px rgba(0, 132, 153, 0.20);
}

#botao-medflow:hover {
    transform: translateY(-1px);
    filter: brightness(1.04);
}

/* Resposta */
#resposta-medflow {
    background: #f8fcfd;
    border: 1px solid #d8edf1;
    border-radius: 18px;
    padding: 20px;
    min-height: 180px;
}

/* Exemplos */
.examples-title {
    color: #003a6b;
    font-weight: 700;
    margin-top: 22px;
    margin-bottom: 4px;
}

/* Aviso */
.disclaimer {
    margin-top: 24px;
    background: #fffdf5;
    border: 1px solid #f1e2a7;
    border-left: 5px solid #e4b534;
    padding: 16px 18px;
    border-radius: 12px;
    color: #6c5a24;
    font-size: 13px;
    line-height: 1.5;
}

/* Rodapé */
.footer-medflow {
    margin-top: 36px;
    padding: 24px 0 8px 0;
    border-top: 1px solid #dce9ee;
    text-align: center;
    color: #718792;
    font-size: 12px;
}

/* Remove alguns fundos padrão */
.block {
    box-shadow: none;
}
"""


with gr.Blocks(
    title="MedFlow AI",
    css=css_medflow,
    theme=gr.themes.Soft(
        primary_hue="cyan",
        secondary_hue="blue",
        neutral_hue="slate"
    )
) as app:

    # HERO
    gr.HTML("""
        <div class="hero-medflow">
            <div class="hero-badge">✦ Inteligência Artificial aplicada à Saúde</div>

            <h1>MedFlow AI</h1>

            <p>
                Assistente inteligente para consulta de protocolos e documentos clínicos,
                desenvolvido com tecnologia RAG para recuperar informações diretamente
                de uma base documental confiável.
            </p>

            <p class="hero-slogan">
                Conectando conhecimento, melhorando decisões, cuidando de vidas.
            </p>
        </div>
    """)

    with gr.Column(elem_id="medflow-main"):

        # Cards informativos
        with gr.Row():

            gr.HTML("""
                <div class="info-card">
                    <h3>📚 Base documental</h3>
                    <p>
                        Consulta protocolos e documentos armazenados na base
                        de conhecimento do MedFlow AI.
                    </p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🔎 Busca semântica</h3>
                    <p>
                        Utiliza embeddings e similaridade para localizar
                        os trechos mais relevantes.
                    </p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🧠 Respostas com RAG</h3>
                    <p>
                        A IA recebe contexto recuperado dos documentos
                        antes de produzir cada resposta.
                    </p>
                </div>
            """)

        # Área de consulta
        with gr.Column(elem_id="consulta-card"):

            gr.HTML("""
                <div class="section-title">
                    Consulte o MedFlow AI
                </div>

                <div class="section-subtitle">
                    Digite uma dúvida relacionada aos documentos disponíveis
                    na base de conhecimento.
                </div>
            """)

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: O que fazer se houver divergência de lateralidade?",
                lines=3,
                elem_id="pergunta-medflow"
            )

            with gr.Row():

                botao = gr.Button(
                    "✦ Perguntar ao MedFlow AI",
                    variant="primary",
                    elem_id="botao-medflow"
                )

                limpar = gr.Button(
                    "Limpar",
                    variant="secondary"
                )

            gr.HTML("""
                <div class="section-title" style="margin-top:25px;">
                    Resposta
                </div>

                <div class="section-subtitle">
                    A resposta será produzida com base no conteúdo recuperado
                    dos documentos.
                </div>
            """)

            resposta = gr.Markdown(
                value="*A resposta do MedFlow AI aparecerá aqui.*",
                elem_id="resposta-medflow"
            )

            gr.HTML("""
                <div class="examples-title">
                    Perguntas para testar
                </div>
                <div class="section-subtitle">
                    Clique em um exemplo para preencher automaticamente o campo.
                </div>
            """)

            gr.Examples(
                examples=[
                    ["O que fazer se o paciente não cumpriu o jejum?"],
                    ["O que fazer quando o paciente relata alergia?"],
                    ["Como proceder se houver divergência de lateralidade?"],
                    ["O que fazer quando um termo obrigatório está pendente?"],
                    ["O que fazer se o sistema apresentar dados de outro paciente?"],
                    ["Qual antibiótico deve ser administrado antes da cirurgia?"]
                ],
                inputs=pergunta
            )

        # Aviso
        gr.HTML("""
            <div class="disclaimer">
                <strong>⚠️ Uso educacional:</strong>
                O MedFlow AI é um projeto acadêmico de demonstração de tecnologia RAG.
                As respostas são baseadas exclusivamente nos documentos disponibilizados
                na base de conhecimento e não substituem avaliação profissional,
                protocolos institucionais, prescrição ou decisão clínica.
            </div>
        """)

        # Footer
        gr.HTML("""
            <div class="footer-medflow">
                <strong>MedFlow AI</strong><br>
                Retrieval-Augmented Generation • Inteligência Artificial • Saúde<br><br>
                Projeto desenvolvido para fins acadêmicos.
            </div>
        """)

    # Ações
    botao.click(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    pergunta.submit(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    limpar.click(
        fn=lambda: ("", "*A resposta do MedFlow AI aparecerá aqui.*"),
        inputs=[],
        outputs=[pergunta, resposta]
    )


print("✅ Nova interface profissional do MedFlow AI criada!")

# ============================================================
# MEDFLOW AI - ETAPA 13.5
# Abrir a interface profissional
# ============================================================

app.launch(
    share=True,
    theme=gr.themes.Soft(
        primary_hue="cyan",
        secondary_hue="blue",
        neutral_hue="slate"
    ),
    css=css_medflow
)

# ============================================================
# MEDFLOW AI - DIAGNÓSTICO DA INTERFACE
# Testar o agente fora do Gradio e medir o tempo
# ============================================================

import time
import traceback

pergunta_teste = "O que fazer se o paciente não cumpriu o jejum?"

inicio_total = time.time()

try:
    print("🔎 1. Buscando contexto...")
    inicio = time.time()

    contexto_teste = montar_contexto(
        pergunta_teste,
        quantidade=3
    )

    print(f"✅ Contexto recuperado em {time.time() - inicio:.2f} segundos")

    print("\n📝 2. Criando prompt...")
    inicio = time.time()

    prompt_teste = criar_prompt(
        pergunta_teste,
        contexto_teste
    )

    print(f"✅ Prompt criado em {time.time() - inicio:.2f} segundos")

    print("\n🤖 3. Consultando Gemini...")
    inicio = time.time()

    resposta_teste = client_gemini.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt_teste
    )

    print(f"✅ Gemini respondeu em {time.time() - inicio:.2f} segundos")

    print("\n" + "=" * 60)
    print("💬 RESPOSTA:")
    print(resposta_teste.text)

    print("\n⏱️ TEMPO TOTAL:")
    print(f"{time.time() - inicio_total:.2f} segundos")

except Exception as erro:
    print("\n❌ ERRO ENCONTRADO:")
    print(type(erro).__name__)
    print(str(erro))

    print("\n📋 DETALHES:")
    traceback.print_exc()

# ============================================================
# MEDFLOW AI - ETAPA 13.6
# Função da interface com carregamento e tratamento de erros
# ============================================================

def interface_medflow(pergunta):

    if not pergunta or not pergunta.strip():
        yield "⚠️ Digite uma pergunta para consultar a base de conhecimento."
        return

    try:

        # Feedback imediato para o usuário
        yield """
### 🔎 Consultando a base de conhecimento...

O MedFlow AI está localizando as informações mais relevantes nos documentos.
"""

        # Recuperação
        contexto = montar_contexto(
            pergunta,
            quantidade=2
        )

        # Prompt
        prompt = criar_prompt(
            pergunta,
            contexto
        )

        # Gemini
        resposta = client_gemini.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        if resposta.text:

            yield f"""
### ✅ Resposta do MedFlow AI

{resposta.text}

---
*Resposta gerada com base na documentação disponível no MedFlow AI.*
"""

        else:

            yield """
### ⚠️ Não foi possível gerar a resposta

Tente novamente em alguns instantes.
"""

    except Exception as erro:

        print("ERRO NA INTERFACE:", repr(erro))

        yield f"""
### ❌ Não foi possível concluir a consulta

Ocorreu um problema durante o processamento da pergunta.

**Detalhe técnico:** `{type(erro).__name__}`

Tente novamente.
"""


print("✅ Função da interface atualizada com sucesso!")

# ============================================================
# MEDFLOW AI - ETAPA 13.7
# Recriar a interface usando a função atualizada
# ============================================================

try:
    app.close()
except:
    pass

import gradio as gr

with gr.Blocks(title="MedFlow AI") as app:

    gr.HTML("""
        <div class="hero-medflow">
            <div class="hero-badge">
                ✦ Inteligência Artificial aplicada à Saúde
            </div>

            <h1>MedFlow AI</h1>

            <p>
                Assistente inteligente para consulta de protocolos e
                documentos clínicos utilizando tecnologia RAG.
            </p>

            <p class="hero-slogan">
                Conectando conhecimento, melhorando decisões, cuidando de vidas.
            </p>
        </div>
    """)

    with gr.Column(elem_id="medflow-main"):

        with gr.Row():
            gr.HTML("""
                <div class="info-card">
                    <h3>📚 Base documental</h3>
                    <p>Consulta informações diretamente dos documentos do MedFlow AI.</p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🔎 Busca semântica</h3>
                    <p>Localiza automaticamente os trechos mais relevantes para cada pergunta.</p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🧠 Tecnologia RAG</h3>
                    <p>A IA responde utilizando o contexto recuperado da base de conhecimento.</p>
                </div>
            """)

        with gr.Column(elem_id="consulta-card"):

            gr.HTML("""
                <div class="section-title">
                    Consulte o MedFlow AI
                </div>

                <div class="section-subtitle">
                    Digite uma dúvida relacionada aos documentos disponíveis
                    na base de conhecimento.
                </div>
            """)

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: O que fazer se o paciente não cumpriu o jejum?",
                lines=3,
                elem_id="pergunta-medflow"
            )

            with gr.Row():

                botao = gr.Button(
                    "✦ Perguntar ao MedFlow AI",
                    variant="primary",
                    elem_id="botao-medflow"
                )

                limpar = gr.Button(
                    "Limpar"
                )

            gr.HTML("""
                <div class="section-title" style="margin-top:25px;">
                    Resposta
                </div>
            """)

            resposta = gr.Markdown(
                value="*A resposta do MedFlow AI aparecerá aqui.*",
                elem_id="resposta-medflow"
            )

            gr.HTML("""
                <div class="examples-title">
                    Perguntas para testar
                </div>
            """)

            gr.Examples(
                examples=[
                    ["O que fazer se o paciente não cumpriu o jejum?"],
                    ["O que fazer quando o paciente relata alergia?"],
                    ["Como proceder se houver divergência de lateralidade?"],
                    ["O que fazer quando um termo obrigatório está pendente?"],
                    ["O que fazer se o sistema apresentar dados de outro paciente?"],
                    ["Qual antibiótico deve ser administrado antes da cirurgia?"]
                ],
                inputs=pergunta
            )

        gr.HTML("""
            <div class="disclaimer">
                <strong>⚠️ Uso educacional:</strong>
                O MedFlow AI é um projeto acadêmico baseado em RAG.
                Não substitui avaliação profissional, prescrição,
                decisão clínica ou protocolos institucionais.
            </div>
        """)

        gr.HTML("""
            <div class="footer-medflow">
                <strong>MedFlow AI</strong><br>
                Retrieval-Augmented Generation • Inteligência Artificial • Saúde
            </div>
        """)

    # NOVA FUNÇÃO ATUALIZADA
    botao.click(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    pergunta.submit(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    limpar.click(
        fn=lambda: (
            "",
            "*A resposta do MedFlow AI aparecerá aqui.*"
        ),
        inputs=[],
        outputs=[pergunta, resposta]
    )

print("✅ Interface reconectada à nova função!")

app.launch(
    share=True,
    theme=gr.themes.Soft(
        primary_hue="cyan",
        secondary_hue="blue",
        neutral_hue="slate"
    ),
    css=css_medflow
)

# ============================================================
# MEDFLOW AI - ETAPA 13.8
# Interface otimizada + resposta em streaming
# ============================================================

def interface_medflow(pergunta):

    if not pergunta or not pergunta.strip():
        yield "⚠️ Digite uma pergunta para consultar a base de conhecimento."
        return

    try:

        # 1. Buscar SOMENTE o melhor resultado
        resultados = buscar_contexto(
            pergunta,
            quantidade=1
        )

        melhor_resultado = resultados[0]

        contexto = f"""
Fonte: {melhor_resultado['fonte']}
Página: {melhor_resultado['pagina']}

{melhor_resultado['texto']}
"""

        # 2. Prompt mais curto
        prompt = f"""
Você é o MedFlow AI.

Responda à pergunta usando somente o contexto abaixo.

Regras:
- Não invente informações.
- Seja objetivo e profissional.
- Se a resposta não estiver no contexto, responda:
"Não encontrei essa informação na base de conhecimento."
- Não faça diagnóstico nem prescrição.
- Informe a fonte ao final.

CONTEXTO:
{contexto}

PERGUNTA:
{pergunta}

RESPOSTA:
"""

        # Feedback inicial
        yield "🔎 **Consultando a base de conhecimento...**"

        # 3. Gemini em STREAMING
        resposta_completa = ""

        stream = client_gemini.models.generate_content_stream(
            model="gemini-3.6-flash",
            contents=prompt
        )

        for parte in stream:

            if parte.text:
                resposta_completa += parte.text

                yield f"""
### 🤖 MedFlow AI

{resposta_completa}
"""

    except Exception as erro:

        print("ERRO:", repr(erro))

        yield f"""
### ❌ Não foi possível concluir a consulta

**Erro:** `{type(erro).__name__}`

Tente novamente.
"""


print("✅ MedFlow AI otimizado para respostas rápidas!")

# ============================================================
# MEDFLOW AI - ETAPA 13.9
# Recriar interface usando resposta em streaming
# ============================================================

try:
    app.close()
except:
    pass

import gradio as gr

with gr.Blocks(title="MedFlow AI") as app:

    gr.HTML("""
        <div class="hero-medflow">
            <div class="hero-badge">
                ✦ Inteligência Artificial aplicada à Saúde
            </div>

            <h1>MedFlow AI</h1>

            <p>
                Assistente inteligente para consulta de protocolos
                e documentos clínicos utilizando tecnologia RAG.
            </p>

            <p class="hero-slogan">
                Conectando conhecimento, melhorando decisões, cuidando de vidas.
            </p>
        </div>
    """)

    with gr.Column(elem_id="medflow-main"):

        with gr.Row():

            gr.HTML("""
                <div class="info-card">
                    <h3>📚 Base documental</h3>
                    <p>
                        Informações recuperadas diretamente dos
                        documentos disponíveis.
                    </p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🔎 Busca semântica</h3>
                    <p>
                        Identificação inteligente dos conteúdos
                        mais relacionados à pergunta.
                    </p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🧠 Tecnologia RAG</h3>
                    <p>
                        Respostas geradas utilizando contexto
                        recuperado da base documental.
                    </p>
                </div>
            """)

        with gr.Column(elem_id="consulta-card"):

            gr.HTML("""
                <div class="section-title">
                    Consulte o MedFlow AI
                </div>

                <div class="section-subtitle">
                    Faça uma pergunta sobre os documentos disponíveis.
                </div>
            """)

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: O que fazer se o paciente não cumpriu o jejum?",
                lines=3,
                elem_id="pergunta-medflow"
            )

            with gr.Row():

                botao = gr.Button(
                    "✦ Perguntar ao MedFlow AI",
                    variant="primary",
                    elem_id="botao-medflow"
                )

                limpar = gr.Button("Limpar")

            gr.HTML("""
                <div class="section-title"
                     style="margin-top:25px;">
                    Resposta
                </div>
            """)

            resposta = gr.Markdown(
                value="*A resposta do MedFlow AI aparecerá aqui.*",
                elem_id="resposta-medflow"
            )

            gr.HTML("""
                <div class="examples-title">
                    Experimente perguntar
                </div>
            """)

            gr.Examples(
                examples=[
                    ["O que fazer se o paciente não cumpriu o jejum?"],
                    ["O que fazer quando o paciente relata alergia?"],
                    ["Como proceder se houver divergência de lateralidade?"],
                    ["O que fazer quando um termo obrigatório está pendente?"],
                    ["O que fazer se o sistema apresentar dados de outro paciente?"]
                ],
                inputs=pergunta
            )

        gr.HTML("""
            <div class="disclaimer">
                <strong>⚠️ Uso educacional:</strong>
                O MedFlow AI é um projeto acadêmico de Inteligência Artificial
                baseado em RAG. Não substitui avaliação profissional,
                prescrição, decisão clínica ou protocolos institucionais.
            </div>
        """)

        gr.HTML("""
            <div class="footer-medflow">
                <strong>MedFlow AI</strong><br>
                RAG • Inteligência Artificial • Saúde
            </div>
        """)

    # STREAMING
    botao.click(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    pergunta.submit(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    limpar.click(
        fn=lambda: (
            "",
            "*A resposta do MedFlow AI aparecerá aqui.*"
        ),
        inputs=[],
        outputs=[pergunta, resposta]
    )

print("✅ Interface rápida criada!")

app.queue()

app.launch(
    share=True,
    theme=gr.themes.Soft(
        primary_hue="cyan",
        secondary_hue="blue",
        neutral_hue="slate"
    ),
    css=css_medflow
)

# ============================================================
# MEDFLOW AI - ETAPA 13.10
# Versão rápida e estável da interface
# ============================================================

def interface_medflow(pergunta):

    if not pergunta or not pergunta.strip():
        return "⚠️ Digite uma pergunta para consultar a base de conhecimento."

    try:

        # 1. Recupera somente o melhor trecho
        resultados = buscar_contexto(
            pergunta,
            quantidade=1
        )

        melhor = resultados[0]

        contexto = f"""
Fonte: {melhor['fonte']}
Página: {melhor['pagina']}

{melhor['texto']}
"""

        # 2. Prompt curto
        prompt = f"""
Você é o MedFlow AI.

Responda somente com base no contexto abaixo.

Regras:
- Não invente informações.
- Seja claro e objetivo.
- Se a resposta não estiver no contexto, diga:
"Não encontrei essa informação na base de conhecimento."
- Não faça diagnóstico ou prescrição.
- Informe a fonte ao final.

CONTEXTO:
{contexto}

PERGUNTA:
{pergunta}

RESPOSTA:
"""

        # 3. Modelo otimizado para baixa latência
        resposta = client_gemini.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt
        )

        if not resposta.text:
            return "⚠️ Não foi possível gerar uma resposta."

        return f"""
### 🤖 MedFlow AI

{resposta.text}

---
*Resposta baseada na documentação disponível.*
"""

    except Exception as erro:

        print("ERRO COMPLETO:", repr(erro))

        return f"""
### ❌ Não foi possível concluir a consulta

**Tipo do erro:** `{type(erro).__name__}`

**Detalhe:** `{str(erro)}`

Tente novamente.
"""


print("✅ MedFlow AI configurado para resposta rápida e estável!")

model="gemini-3.5-flash-lite"

"""✅ MedFlow AI configurado para resposta rápida e estável!"""

import time

inicio = time.time()

resultado = interface_medflow(
    "O que fazer se o paciente não cumpriu o jejum?"
)

tempo = time.time() - inicio

print(resultado)

print("\n" + "=" * 60)
print(f"⚡ Tempo total da resposta: {tempo:.2f} segundos")

# ============================================================
# MEDFLOW AI - ETAPA 13.12
# Recriar interface com a versão rápida e estável
# ============================================================

try:
    app.close()
except:
    pass

import gradio as gr

with gr.Blocks(title="MedFlow AI") as app:

    gr.HTML("""
        <div class="hero-medflow">
            <div class="hero-badge">
                ✦ Inteligência Artificial aplicada à Saúde
            </div>

            <h1>MedFlow AI</h1>

            <p>
                Assistente inteligente para consulta de protocolos
                e documentos clínicos utilizando tecnologia RAG.
            </p>

            <p class="hero-slogan">
                Conectando conhecimento, melhorando decisões, cuidando de vidas.
            </p>
        </div>
    """)

    with gr.Column(elem_id="medflow-main"):

        with gr.Row():
            gr.HTML("""
                <div class="info-card">
                    <h3>📚 Base documental</h3>
                    <p>Consulta informações diretamente dos documentos disponíveis.</p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🔎 Busca semântica</h3>
                    <p>Localiza o trecho mais relevante para cada pergunta.</p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🧠 Tecnologia RAG</h3>
                    <p>Responde utilizando contexto recuperado da base documental.</p>
                </div>
            """)

        with gr.Column(elem_id="consulta-card"):

            gr.HTML("""
                <div class="section-title">
                    Consulte o MedFlow AI
                </div>

                <div class="section-subtitle">
                    Faça uma pergunta relacionada à base de conhecimento.
                </div>
            """)

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: O que fazer se o paciente não cumpriu o jejum?",
                lines=3,
                elem_id="pergunta-medflow"
            )

            with gr.Row():
                botao = gr.Button(
                    "✦ Perguntar ao MedFlow AI",
                    variant="primary",
                    elem_id="botao-medflow"
                )

                limpar = gr.Button("Limpar")

            gr.HTML("""
                <div class="section-title" style="margin-top:25px;">
                    Resposta
                </div>
            """)

            resposta = gr.Markdown(
                value="*A resposta do MedFlow AI aparecerá aqui.*",
                elem_id="resposta-medflow"
            )

            gr.Examples(
                examples=[
                    ["O que fazer se o paciente não cumpriu o jejum?"],
                    ["O que fazer quando o paciente relata alergia?"],
                    ["Como proceder se houver divergência de lateralidade?"],
                    ["O que fazer quando um termo obrigatório está pendente?"],
                    ["O que fazer se o sistema apresentar dados de outro paciente?"]
                ],
                inputs=pergunta
            )

        gr.HTML("""
            <div class="disclaimer">
                <strong>⚠️ Uso educacional:</strong>
                O MedFlow AI é um projeto acadêmico baseado em RAG.
                Não substitui avaliação profissional, prescrição,
                decisão clínica ou protocolos institucionais.
            </div>
        """)

        gr.HTML("""
            <div class="footer-medflow">
                <strong>MedFlow AI</strong><br>
                RAG • Inteligência Artificial • Saúde
            </div>
        """)

    botao.click(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    pergunta.submit(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    limpar.click(
        fn=lambda: (
            "",
            "*A resposta do MedFlow AI aparecerá aqui.*"
        ),
        inputs=[],
        outputs=[pergunta, resposta]
    )

print("✅ Interface conectada à versão rápida!")

app.launch(
    share=True,
    theme=gr.themes.Soft(
        primary_hue="cyan",
        secondary_hue="blue",
        neutral_hue="slate"
    ),
    css=css_medflow
)

# ============================================================
# MEDFLOW AI - ETAPA 13.13
# Upload da identidade visual
# ============================================================

from google.colab import files

logo_upload = files.upload()

print("✅ Logo enviada para o Colab!")

import os

arquivos_logo = [
    arquivo
    for arquivo in os.listdir("/content")
    if arquivo.lower().endswith((".png", ".jpg", ".jpeg"))
]

print("🖼️ Imagens encontradas:\n")

for arquivo in arquivos_logo:
    print("-", arquivo)

import os

arquivos_logo = [
    arquivo
    for arquivo in os.listdir("/content")
    if arquivo.lower().endswith((".png", ".jpg", ".jpeg"))
]

print("🖼️ Imagens encontradas no Colab:\n")

for arquivo in arquivos_logo:
    print("-", arquivo)

# ============================================================
# MEDFLOW AI - ETAPA 13.14
# Converter a logo para exibição na interface
# ============================================================

import base64

logo_path = "/content/MedFlow_AI_nova_identidade.png"

with open(logo_path, "rb") as imagem:
    logo_base64 = base64.b64encode(imagem.read()).decode("utf-8")

print("✅ Logo preparada para uso na interface!")

# ============================================================
# MEDFLOW AI - ETAPA 13.15
# Interface com logo oficial integrada
# ============================================================

try:
    app.close()
except:
    pass

import gradio as gr

hero_com_logo = f"""
<div class="hero-medflow" style="
    display:flex;
    align-items:center;
    justify-content:space-between;
    gap:40px;
    flex-wrap:wrap;
">
    <div style="flex:1; min-width:320px;">
        <div class="hero-badge">
            ✦ Inteligência Artificial aplicada à Saúde
        </div>

        <h1 style="margin-top:10px;">MedFlow AI</h1>

        <p>
            Assistente inteligente para consulta de protocolos e
            documentos clínicos utilizando tecnologia RAG.
        </p>

        <p class="hero-slogan">
            Conectando conhecimento, melhorando decisões, cuidando de vidas.
        </p>
    </div>

    <div style="
        flex:0 0 340px;
        text-align:center;
    ">
        <img
            src="data:image/png;base64,{logo_base64}"
            style="
                max-width:320px;
                width:100%;
                height:auto;
                filter:drop-shadow(0 16px 28px rgba(0,0,0,0.18));
            "
        />
    </div>
</div>
"""

with gr.Blocks(title="MedFlow AI") as app:

    gr.HTML(hero_com_logo)

    with gr.Column(elem_id="medflow-main"):

        with gr.Row():

            gr.HTML("""
                <div class="info-card">
                    <h3>📚 Base documental</h3>
                    <p>
                        Consulta informações diretamente dos documentos
                        disponíveis na base de conhecimento.
                    </p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🔎 Busca semântica</h3>
                    <p>
                        Localiza automaticamente os trechos mais relevantes
                        para cada pergunta.
                    </p>
                </div>
            """)

            gr.HTML("""
                <div class="info-card">
                    <h3>🧠 Tecnologia RAG</h3>
                    <p>
                        Respostas geradas com contexto recuperado da
                        documentação do MedFlow AI.
                    </p>
                </div>
            """)

        with gr.Column(elem_id="consulta-card"):

            gr.HTML("""
                <div class="section-title">
                    Consulte o MedFlow AI
                </div>

                <div class="section-subtitle">
                    Digite sua dúvida e consulte a base documental inteligente.
                </div>
            """)

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: O que fazer se o paciente não cumpriu o jejum?",
                lines=3,
                elem_id="pergunta-medflow"
            )

            with gr.Row():

                botao = gr.Button(
                    "✦ Perguntar ao MedFlow AI",
                    variant="primary",
                    elem_id="botao-medflow"
                )

                limpar = gr.Button("Limpar")

            gr.HTML("""
                <div class="section-title" style="margin-top:25px;">
                    Resposta
                </div>
            """)

            resposta = gr.Markdown(
                value="*A resposta do MedFlow AI aparecerá aqui.*",
                elem_id="resposta-medflow"
            )

            gr.HTML("""
                <div class="examples-title">
                    Experimente perguntar
                </div>
            """)

            gr.Examples(
                examples=[
                    ["O que fazer se o paciente não cumpriu o jejum?"],
                    ["O que fazer quando o paciente relata alergia?"],
                    ["Como proceder se houver divergência de lateralidade?"],
                    ["O que fazer quando um termo obrigatório está pendente?"],
                    ["O que fazer se o sistema apresentar dados de outro paciente?"]
                ],
                inputs=pergunta
            )

        gr.HTML("""
            <div class="disclaimer">
                <strong>⚠️ Uso educacional:</strong>
                O MedFlow AI é um projeto acadêmico baseado em RAG.
                Não substitui avaliação profissional, prescrição,
                decisão clínica ou protocolos institucionais.
            </div>
        """)

        gr.HTML("""
            <div class="footer-medflow">
                <strong>MedFlow AI</strong><br>
                RAG • Inteligência Artificial • Saúde
            </div>
        """)

    botao.click(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    pergunta.submit(
        fn=interface_medflow,
        inputs=pergunta,
        outputs=resposta
    )

    limpar.click(
        fn=lambda: (
            "",
            "*A resposta do MedFlow AI aparecerá aqui.*"
        ),
        inputs=[],
        outputs=[pergunta, resposta]
    )

print("✅ Interface com logo oficial criada!")

app.launch(
    share=True,
    theme=gr.themes.Soft(
        primary_hue="cyan",
        secondary_hue="blue",
        neutral_hue="slate"
    ),
    css=css_medflow
)